<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-06-09T18:54:43 IST" name="Suite" finished-at="2023-06-09T18:55:24 IST" duration-ms="41593">
    <groups>
    </groups>
    <test started-at="2023-06-09T18:54:43 IST" name="Test" finished-at="2023-06-09T18:55:24 IST" duration-ms="41593">
      <class name="TestCases.verifySignUpPage">
        <test-method is-config="true" signature="Exicution()[pri:0, instance:TestCases.verifySignUpPage@459e9125]" started-at="2023-06-09T18:55:07 IST" name="Exicution" finished-at="2023-06-09T18:55:12 IST" duration-ms="5439" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Exicution -->
        <test-method signature="signUp()[pri:0, instance:TestCases.verifySignUpPage@459e9125]" started-at="2023-06-09T18:55:12 IST" name="signUp" finished-at="2023-06-09T18:55:24 IST" duration-ms="11687" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- signUp -->
        <test-method is-config="true" signature="quitBrowser()[pri:0, instance:TestCases.verifySignUpPage@459e9125]" started-at="2023-06-09T18:55:24 IST" name="quitBrowser" finished-at="2023-06-09T18:55:24 IST" duration-ms="416" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quitBrowser -->
      </class> <!-- TestCases.verifySignUpPage -->
      <class name="TestCases.Verify">
        <test-method is-config="true" signature="Exicution()[pri:0, instance:TestCases.Verify@c8c12ac]" started-at="2023-06-09T18:54:43 IST" name="Exicution" finished-at="2023-06-09T18:55:06 IST" duration-ms="22787" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Exicution -->
        <test-method signature="failedlogin()[pri:0, instance:TestCases.Verify@c8c12ac]" started-at="2023-06-09T18:55:06 IST" name="failedlogin" finished-at="2023-06-09T18:55:06 IST" duration-ms="525" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
Testfail expected [Please check your  and password. If you still can't log in, contact your Salesforce administrator.] but found []]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
Testfail expected [Please check your  and password. If you still can't log in, contact your Salesforce administrator.] but found []
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at resourses.commonMethods.HandleAssertion(commonMethods.java:19)
at TestCases.Verify.failedlogin(Verify.java:50)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failedlogin -->
        <test-method is-config="true" signature="quitBrowser()[pri:0, instance:TestCases.Verify@c8c12ac]" started-at="2023-06-09T18:55:06 IST" name="quitBrowser" finished-at="2023-06-09T18:55:07 IST" duration-ms="598" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quitBrowser -->
      </class> <!-- TestCases.Verify -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
